name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Указываем нужную версию Python

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install

      - name: Run lint
        run: make lint

      - name: Run tests
        run: poetry run pytest

      - name: Upload coverage to CodeClimate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          pip install codeclimate-test-reporter
          codeclimate-test-reporter before-build
          poetry run pytest --cov=gendiff --cov-report xml:coverage.xml
          codeclimate-test-reporter after-build
